package com.springmvc.Bean;

import org.hibernate.validator.constraints.NotBlank;
import org.springframework.stereotype.Component;

import java.util.Date;


@Component
public class UserImpl implements User {

    //Auto-generated by MariaDB
    private int id;

    @NotBlank(message="Username can't be empty")
    private String username;

    @NotBlank(message="Password can't be empty")
    private String password;

    private boolean enabled;

    private String firstname;

    private String lastname;

    @NotBlank(message = "Email can't be empty")
    private String email;

    //Auto-generated by MariaDB
    private Date created;

    @Override
    public int getId() {
        return id;
    }

    @Override
    public void setId(int id) {
        this.id = id;
    }

    @Override
    public String getUsername() {
        return username;
    }

    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }

    @Override
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String getFirstname() {
        return firstname;
    }

    @Override
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Override
    public String getLastname() {
        return lastname;
    }

    @Override
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Override
    public String getEmail() {
        return email;
    }

    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public Date getCreated() {
        return created;
    }

    @Override
    public void setCreated(Date created) {
        this.created = created;
    }
}
