package com.springmvc.Bean;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;
import org.springframework.stereotype.Service;

import javax.validation.constraints.Size;
import java.util.Date;

@Service
public class User{

    //Auto-generated by MariaDB
    private int id;

    @NotBlank(message="Username is required.")
    @Size(min=3, message="Please enter at least 3 characters.")
    private String username;

    @NotBlank(message="Password is required.")
    @Size(min=5, message="Please enter at least 5 characters.")
    private String password;

    private boolean enabled;

    private String firstname;

    private String lastname;

    @Email(message = "Email is required.")
    private String email;

    //Auto-generated by MariaDB
    private Date created;

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isEnabled() {
        return enabled;
    }
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getFirstname() {
        return firstname;
    }
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    public Date getCreated() {
        return created;
    }
    public void setCreated(Date created) {
        this.created = created;
    }
}
