<%@page contentType="text/html;charset=UTF-8" language="java"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@taglib prefix="sec" uri="http://www.springframework.org/security/tags"%>
<sec:authorize access="isAuthenticated()">
<c:set var="principalUsername">
    <sec:authentication property="principal.username" />
</c:set>
</sec:authorize>
<!DOCTYPE html>
<html>
<head>
    <!-- Links and scripts (tag file) -->
    <t:dependencies></t:dependencies>

    <!-- Templating for first column's data -->
    <script type="text/template" id="template-column-one">
        {{#.}}
            <li value="{{id}}"><a href="#" data-toggle="tab">{{name}}</a></li>
        {{/.}}
    </script>

    <!-- Templating for second column's data -->
    <script type="text/template" id="template-column-two">
        {{#.}}
            <li value="{{id}}"><a href="{{id}}" data-toggle="tab">{{name}}</a></li>
        {{/.}}
    </script>

    <!-- Templating for third column's data -->
    <script type="text/template" id="template-column-three">
        <h1>{{name}}</h1>
        {{#beerPackage}}
        <p class="price">{{price}} € <span class="size">{{aPackage.size}}l</span><br></p>
        <p class="per-liter">{{pricePerLiter}} €/l</p>
        {{/beerPackage}}

        <div class="title">
            <h2>Description</h2>
        </div>
        <p>Contains {{alcohol}}% percent of alcohol. {{description}}</p>
        <hr>

        <div class="title">
            <h2>Brewery</h2>
        </div>
        {{#brewery}}
        <p>{{name}}, {{country.name}}</p>
        {{/brewery}}
        <hr>

        <div class="title">
            <h2>Uploader</h2>
        </div>
        {{#user}}
        <p>{{username}} on {{created}}</p>
        {{/user}}
        <hr>

        <div class="title">
            <h2>Rating</h2>
        </div>

    </script>
</head>
<body>
<!-- Navigation bar (tag file) -->
<t:navigationbar></t:navigationbar>

<!-- Actual body of the site -->
<div class="container-fluid introduction">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 text-center">
            <span class="vertical-align">
                <h1>Database for Beers and Brewerys</h1>

                    <!-- Introduction text for unregistered user -->
                    <sec:authorize access="isAnonymous()">
                    <p class="lead">BeerDB is your database for delicious beers and wonderful brewerys.
                        <a href="${context}/signup" type="submit">Sign Up</a> and you can post your own beers to database and
                        rate them. So much wow. Free-time project.
                    </p>
                    </sec:authorize>

                    <!-- Introduction text for registered user -->
                    <sec:authorize access="isAuthenticated()">
                    <p class="lead">You are logged in as "${principalUsername}"
                        and this text is mainly placeholder. </p>

                     <!-- "You added beer to db" -->
                     <p class="bg-success">${beerAdded}</p>
                    </sec:authorize>
            </span>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="menu">
            <!-- COLUMN ONE. Menu where beerstyles are listed -->
            <div class="col-lg-3">
                <ul id="column-one-content" class="nav nav-pills nav-stacked" role="tablist" data-tabs="tabs">
                <!-- Data for li-elements are dynamically generated by appendResponseToColumnOne -function in callajax.js -->
                </ul>
             </div>

            <!-- COLUMN TWO. Menu where beers are listed by chosen beerstyle -->
            <div class="col-lg-3">
                <div id="my-tab-content" class="tab-content">
                     <ul id="column-two-content" class="nav nav-pills nav-stacked" role="tablist" data-tabs="tabs">
                     <!-- Data for li-elements are dynamically generated by appendResponseToColumnTwo -function in callajax.js -->
                     </ul>
                </div>
            </div>

            <!-- COLUMN THREE. All the information about chosen beer -->
            <div class="col-lg-6">
                    <div id="column-three-content" class="tab-content">
                    <!-- Data for this div is dynamically generated in appendResponseToColumnThree -function in callajax.js  -->
                    </div>
            </div>
        </div> <!-- menu -->
    </div> <!-- row -->
</div> <!-- container -->

<!-- Success modal for completed registration -->
<div class="modal" id="registration-success-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div id="loginbox" class="mainbox col-sm-8 col-sm-offset-2">
            <div class="panel panel-info" >
                <!-- Modal head -->
                <div class="panel-heading">
                    <div class="panel-title">Great success ${username}!</div>
                    <button type="button" class="close login-close-button" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                </div>
                <!-- Modal body -->
                <div id="login-panel-body" class="panel-body" >
                    You just made a new account! Now you can sign in with your username and password.
                </div> <!-- login-panel-body -->
            </div> <!-- panel -->
        </div> <!-- loginbox -->
    </div> <!-- modal-dialog -->
</div> <!-- modal -->

<!-- Opens success modal -->
<script>
    $(document).ready(function() {
        <c:if test="${openSuccessModal == true}">
        $('#registration-success-modal').modal('show');
        </c:if>
    });
</script>

<!-- Footer (tag file) -->
<t:footer></t:footer>
</body>
</html>