<%@page contentType="text/html;charset=UTF-8" language="java"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html>
<head>
    <title>BeerDB</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
    <link href="resources/css/bootstrap.css" rel="stylesheet" type="text/css"/>
    <link href="resources/css/style.css" rel="stylesheet" type="text/css"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.js"></script>
    <script src="resources/js/callajax.js" type="text/javascript"></script>
    <script src="resources/js/formvalidation.js" type="text/javascript"></script>
    <script src="resources/js/beerdb.js" type="text/javascript"></script>

    <!-- MUSTACHE.JS TEMPLATING -->
    <!-- Templating for first column's data -->
    <script type="text/template" id="template-column-one">
        {{#.}}
            <li value="{{id}}"><a href="#" data-toggle="tab">{{name}}</a></li>
        {{/.}}
    </script>

    <!-- Templating for second column's data -->
    <script type="text/template" id="template-column-two">
        {{#.}}
            <li value="{{id}}"><a href="{{name}}" data-toggle="tab">{{name}}</a></li>
        {{/.}}
    </script>

    <!-- Templating for third column's data -->
    <script type="text/template" id="template-column-three">
        <h1 align="center">{{name}}</h1>
        <br>
        <p>Process: {{process}}</p>
        {{#user}}
        <p>Uploaded by {{username}} on {{created}}</p>
        {{/user}}
        {{brewery.name}}
        <p>Not much to see here yet</p>
    </script>
</head>

<body>


<!-- Page header comes from JSP Tags. It changes depending on the user role. This is for unregistered user -->
<t:unregistereduser>
    <jsp:attribute name="header">
    </jsp:attribute>
</t:unregistereduser>

<div class="container">
    <div class="row">
        <!-- Introduction text -->
        <div class="col-lg-12 text-center">
            <h1>Database for Beers and Brewerys</h1>
            <p class="lead">BeerDB is your database for delicious beers and wonderful brewerys. Sign Up
            and you can post your own beers to database and even rate them (well, not yet, but it's coming soon..)!
            So much wow. Freetime project.</p>
        </div>
    </div>

    <div class="row">
        <div class="menu">
            <!-- COLUMN ONE. Menu where beerstyles are listed -->
            <div class="col-lg-3">
                <ul id="column-one-content" class="nav nav-pills nav-stacked" role="tablist" data-tabs="tabs">
                <!-- Data for li-elements are dynamically generated by appendResponseToColumnOne -function in callajax.js -->
                </ul>
             </div>

            <!-- COLUMN TWO. Menu where beers are listed by chosen beerstyle -->
            <div class="col-lg-3">
                <div id="my-tab-content" class="tab-content">
                    <div class="tab-pane active">
                         <ul id="column-two-content" class="nav nav-pills nav-stacked" role="tablist" data-tabs="tabs">
                         <!-- Data for li-elements are dynamically generated by appendResponseToColumnTwo -function in callajax.js -->
                         </ul>
                    </div>
                </div>
            </div>

            <!-- COLUMN THREE. All the information about chosen beer -->
            <div class="col-lg-6">
                    <div id="column-three-content" class="tab-content">
                    <!-- Data for this div is dynamically generated in appendResponseToColumnThree -function in callajax.js  -->
                    </div>
            </div>
        </div> <!-- menu -->
    </div> <!-- row -->

</div> <!-- container -->

<!-- Footer -->
<div class="footer navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <a target="_blank" href="https://github.com/juhaniniinimaa/beerdb">
                    <img src="resources/logos/GitHub-Mark-32px.png" alt="GitHub"></a>
            </div>
        </div>
    </div>
</div>


<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>